
[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "https://github.com/4r75y4n4rch157/portfolio/master/node0/Assets/MirrorMove.mp4" 